---
development:
  cloud_name: hxwdzwkhn
  api_key: '756821587929877'
  api_secret: e9lQ2DkvauQHdG065byfWeUp7QQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hxwdzwkhn
  api_key: '756821587929877'
  api_secret: e9lQ2DkvauQHdG065byfWeUp7QQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hxwdzwkhn
  api_key: '756821587929877'
  api_secret: e9lQ2DkvauQHdG065byfWeUp7QQ
  enhance_image_tag: true
  static_image_support: false
